on:
  workflow_dispatch:

jobs:
  get-tags:
    name: Get a list of tags we need to build
    runs-on: ubuntu-latest
    outputs:
      tags_json: ${{ steps.tags-to-build.tags_json }} 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".github/workflows/.python-version"

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: ".github/workflows/requirements.txt"

      - name: Run Python script
        id: tags-to-build
        run: python ".github/workflows/check.py" >> $GITHUB_OUTPUT

## runs-on: ${{ fromJson(inputs.runner_labels) }}
        
  build-container:
    name: Build EGAPx containers
    runs-on: ubuntu-latest
    needs: get-tags
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
   
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: ${{ fromJSON(needs.get-tags.outputs.tags_json) }}
          context: ".github/docker"
