on:
  workflow_dispatch:

jobs:
  get-egapx-tags:
    name: Get a list of EGPAx tags we need to build
    runs-on: ubuntu-latest

    outputs:
      egapx_tags: ${{ steps.get-tags.outputs.egapx_tags }} 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".github/workflows/.python-version"

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: ".github/workflows/requirements.txt"

      - name: Run Python script
        id: get-tags
        run: python ".github/workflows/check.py" >> "$GITHUB_OUTPUT"

  build-egapx-containers:
    name: Build EGAPx containers
    runs-on: ubuntu-latest
    needs: get-egapx-tags
    strategy:
      matrix:
        egapx_tag: ${{ fromJSON(needs.get-egapx-tags.outputs.egapx_tags) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args:
            - BUILD_SRC=docker.io/ncbi/egapx:${{ matrix.egapx_tag }}
          context: ".github/docker"
          no-cache: true
          platforms: linux/amd64
          push: true
          tags: egpax:${{ matrix.egapx_tag }}
