on:
  workflow_dispatch:

jobs:
  get-data:
    name: get-data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".github/workflows/.python-version"

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: ".github/workflows/requirements.txt"

      - name: Run Python script
        run: python ".github/workflows/check.py" >> $GITHUB_OUTPUT
  foo:
    name: foo
    runs-on: ubuntu-latest
    needs: get-data
    strategy:
      matrix:
        build_tags: ${{ fromJSON(needs.job1.outputs.tags_json }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
   
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}#

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:.github/docker"
